name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.7
  - pandas=1.2.3
  - pip=20.3.3
  - mlflow=2.1.1
  - scikit-learn=0.24.1
  # - matplotlib=2.1.1
  # - pillow=9.4.0
  # - click=8.1.3
  - pip:
      - wandb==0.12.17
